# Environment Settings
environment:
  width: 200
  height: 200
  num_sensors: 50
  num_obstacles: 5
  coverage_ratio: 0.2

# Path Representation
path:
  dx: 5
  length_max: 2000.0

# Exposure Calculation
exposure:
  step: 1.0

# Repair Parameters
repair:
  attempts: 100

# Sensor & Obstacle Settings
sensor:
  radius_min: 5
  radius_max: 50
  power: 1.0

obstacle:
  min_distance: 5
  min_area: 50
  radius_min: 15
  radius_max: 75
  vertices_min: 4
  vertices_max: 8

algorithm:

  sac:
    pop_size: 40
    n_generations: 100
    updates_per_ep: 10
    batch_size: 128

    hidden_size: 256
    lr: 0.001

    alpha_init: 1.0
    tau: 0.005

    action_scale: 15.0
    w1: 0.9
    w2: 0.1
    window_size: 5


  moead:
    pop_size: 100
    n_generations: 100
    neighborhood_size: 15
    crossover_prob: 0.9
    mutation_prob: 0.4
    eta_c: 10
    eta_m: 10


  ppo:
      n_steps: 2048          # Số bước chạy trước khi cập nhật
      batch_size: 64         # Kích thước batch để training
      n_epochs: 12          # Số lần training lại trên cùng dữ liệu
      lr: 0.0001             # Learning rate
      gamma: 0.99            # Hệ số chiết khấu (Discount factor)
      gae_lambda: 0.95       # Hệ số GAE để tính advantage
      clip_range: 0.3        # Tham số chặn của PPO
      ent_coef: 0.04         # Hệ số entropy để khuyến khích khám phá
      pop_size: 1            # Thường PPO chạy đơn lẻ hoặc song song, ở đây ta chạy đơn
      n_generations: 1000     # Số tập (episodes) training


  td3:
      n_episodes: 1000          # Số lượng episodes (Nên để bằng n_generations của PPO)
      batch_size: 256           # Cỡ batch lấy từ Replay Buffer (để 256 giúp hàm loss mượt hơn)
      hidden_size: 256          # Số node ẩn trong mạng Actor/Critic
      lr: 0.001                 # Learning rate (TD3 có thể học với lr lớn hơn PPO một chút)
      gamma: 0.99               # Hệ số chiết khấu
      tau: 0.005                # Hệ số cập nhật mềm cho Target Net

      # TD3 Specific Parameters
      action_scale: 15.0        # Giới hạn dịch chuyển trục Y (Max Action).
      exploration_noise: 2.0    # Nhiễu Gaussian thêm vào action để tìm đường mới (giảm từ 5.0 xuống 2.0 để tránh bay loạn xạ)
      policy_noise: 2.0         # Nhiễu thêm vào Target Policy Net để chống overestimation
      noise_clip: 5.0           # Giới hạn cắt của policy_noise
      policy_freq: 2            # Tần suất cập nhật mạng Actor (Đặc trưng của Delayed TD3)
      max_replay_buffer: 100000 # Kích thước bộ nhớ lưu trữ kinh nghiệm

      # Reward weights (Khớp với PPO: Exp * 1.5 - Len * 0.05)
      w_exp: 1.5                # Trọng số cho Reward Exposure
      w_len: 0.05               # Trọng số phạt cho Reward Length